name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # 当推送到 dev 分支时触发
  workflow_dispatch:  # 添加手动触发的功能
  
env:
  IMAGE_NAME: cloudflarespeedtest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 Docker Buildx，启用跨平台构建支持
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 登录到 Docker Hub
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: echo $ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

    # 构建和推送 Docker 镜像（支持多平台）
    - name: Build and Push Docker Image for x86 and ARM riscv64
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
      run: |
        IMAGE_ID=$DOCKER_USERNAME/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # 获取 GitHub 事件负载中的分支名
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # 根据分支选择版本号
        if [ "$BRANCH_NAME" == "master" ]; then
          VERSION="latest"
        else
          VERSION="$BRANCH_NAME.${{ github.run_number }}"
        fi

        echo "IMAGE_ID=$IMAGE_ID"
        echo "VERSION=$VERSION"

        # 使用 docker buildx 构建并推送多平台镜像
        docker buildx build --platform linux/amd64,linux/arm64,linux/386,linux/riscv64 -f Dockerfile -t $IMAGE_ID:$VERSION . --push

        # 打印构建成功的版本信息
        echo "Successfully built and pushed $IMAGE_ID:$VERSION"
